
export const fontMapping = {
    "mathrm": "upright",
    "mbox": "upright",
    "hbox": "upright",
    "mathit": "italic",
    "mathsf": "sans",
    "mathtt": "mono",
    "mathbb": "bb",
    "mathcal": "cal",
    // there's no independent impl for mathscr in typst currently
    "mathscr": "cal",
    "mathfrak": "frak",
    "mathnormal": "",
    "boldsymbol": "bold",
};

export const mathordMapping = {
    "\\alpha": "α",
    "\\beta": "β",
    "\\gamma": "γ",
    "\\delta": "δ",
    "\\epsilon": "ϵ",
    "\\zeta": "ζ",
    "\\eta": "η",
    "\\theta": "θ",
    "\\iota": "ι",
    "\\kappa": "κ",
    "\\lambda": "λ",
    "\\mu": "μ",
    "\\nu": "ν",
    "\\xi": "ξ",
    "\\omicron": "ο",
    "\\pi": "π",
    "\\rho": "ρ",
    "\\sigma": "σ",
    "\\tau": "τ",
    "\\upsilon": "υ",
    "\\phi": "ϕ",
    "\\chi": "χ",
    "\\psi": "ψ",
    "\\omega": "ω",
    "\\varepsilon": "ε",
    "\\varphi": "φ",
    "\\varpi": "ϖ",
    "\\varrho": "ϱ",
    "\\varsigma": "ς",
    "\\vartheta": "ϑ",
    "\\imath": "𝚤",
    "\\@imath": "𝚤",
    "\\jmath": "𝚥",
    "\\@jmath": "𝚥",
}

export const textordMapping = {
    "\\varvdots": "⋮",
    "/": "/",
    "\\_": "_",
    "\\|": "‖",
    "\\%": "%",
    "\\$": "$",
    "\\{": "{",
    "\\}": "}",
    "\\[": "[",
    "\\]": "]",
    "\\vert": "|",
    "\\Vert": "‖",
    "\\Gamma": "Γ",
    "\\Delta": "Δ",
    "\\Theta": "Θ",
    "\\Lambda": "Λ",
    "\\Xi": "Ξ",
    "\\Pi": "Π",
    "\\Sigma": "Σ",
    "\\Upsilon": "Υ",
    "\\Phi": "Φ",
    "\\Psi": "Ψ",
    "\\Omega": "Ω",
    "\\varkappa": "ϰ",
    "\\ell": "ℓ",
    "\\infty": "∞",
    "\\lbrack": "[",
    "\\rbrack": "]",
    "\\angle": "∠",
    "\\measuredangle": "∡",
    "\\sphericalangle": "∢",
    "\\checkmark": "✓",
    "\\backslash": "\\",
    "\\prime": "′",
    "\\backprime": "‵",
    "\\emptyset": "∅",
    "\\varnothing": "∅",
    "\\o": "∅",
    "\\O": "∅",
    "\\complement": "∁",
    "\\partial": "∂",
    "\\nabla": "∇",
    "\\forall": "∀",
    "\\exists": "∃",
    "\\nexists": "∄",
    "\\top": "⊤",
    "\\bot": "⊥",
    "\\neg": "¬",
    "\\lnot": "¬",
    "\\blacksquare": "∎",
    "\\pounds": "£",
    "\\clubsuit": "♣",
    "\\spadesuit": "♠",
    "\\triangle": "△",
    "\\triangledown": "▿",
    "\\square": "□",
    "\\Diamond": "◇",
    "\\diamondsuit": "◇",
    "\\lozenge": "◊",
    "\\blacklozenge": "⧫",
    "\\bigstar": "☆",
    "\\hbar": "ℏ",
    "\\hslash": "ℏ",
    "\\Re": "ℜ",
    "\\Im": "ℑ",
    "\\Box": "☐",
    "\\natural": "♮",
    "\\P": "¶",
    "\\S": "§",
    "\\AE": "Æ",
    "\\ae": "æ",
    "\\aleph": "א",
    "\\dag": "†",
    "\\ddag": "‡",
    "\\daleth": "ℸ",
    "\\sharp": "♯",
    "\\flat": "♭",
    "\\i": "𝚤",
    "\\j": "𝚥",
    "\\ss": "ß",
    "\\surd": "√",
    "\\wp": "℘",
    "\\beth": "ב",
    "\\blacktriangle": "▲",
    "\\blacktriangledown": "▼",
    "\\circledR": "®",
    "\\circledS": "Ⓢ",
    "\\degree": "°",
    "\\digamma": "ϝ",
    "\\diagdown": "╲",
    "\\diagup": "╱",
    "\\eth": "ð",
    "\\Finv": "Ⅎ",
    "\\Game": "⅁",
    "\\gimel": "ג",
    "\\heartsuit": "♡",
    "\\maltese": "✠",
    "\\mathsterling": "£",
    "\\mho": "℧",
    "\\OE": "Œ",
    "\\oe": "œ",
    "\\textasciitilde": "~",
    "\\textasciicircum": "^",
    "\\textbackslash": "\\",
    "\\textbar": "|",
    "\\textbardbl": "‖",
    "\\textbraceleft": "{",
    "\\textbraceright": "}",
    "\\textdagger": "†",
    "\\textdaggerdbl": "‡",
    "\\textdegree": "°",
    "\\textemdash": "−",
    "\\textendash": "−",
    "\\textgreater": ">",
    "\\textless": "<",
    "\\textquotedblleft": "“",
    "\\textquotedblright": "”",
    "\\textquoteleft": "‘",
    "\\textquoteright": "’",
    "\\textsterling": "£",
    "\\textunderscore": "_",
    "\\yen": "¥",
}

export const relMapping = {
    "=": "=",
    ">": ">",
    "<": "<",
    "≤": "≤",
    ":": ":",
    "↦": "↦",
    "≅": "≅",
    "∈": "∈",

    // fallback
    "\\@not": "",

    "\\in": "∈",
    "\\subset": "⊂",
    "\\subseteq": "⊆",
    "\\subsetneqq": "⫋",
    "\\lt": "<",
    "\\le": "≤",
    "\\ge": "≥",
    "\\leq": "≤",
    "\\geq": "≥",
    "\\leqslant": "⩽",
    "\\geqslant": "⩾",
    "\\eqslantgtr": "⪖",
    "\\eqslantless": "⪕",
    "\\approx": "≈",
    "\\leftarrow": "←",
    "\\rightarrow": "→",
    "\\leftrightarrow": "↔",
    "\\Leftarrow": "⇐",
    "\\Rightarrow": "⇒",
    "\\Leftrightarrow": "⇔",
    "\\longleftarrow": "⟵",
    "\\longrightarrow": "⟶",
    "\\longleftrightarrow": "⟷",
    "\\Longleftarrow": "⟸",
    "\\Longrightarrow": "⟹",
    "\\Longleftrightarrow": "⟺",
    "\\to": "→",
    "\\gets": "←",
    "\\mapsto": "↦",
    "\\sim": "∼",
    "\\simeq": "≃",
    "\\backsimeq": "⋍",
    "\\cong": "≅",
    "\\ncong": "≇",
    "\\nsim": "≁",
    "\\backsim": "∽",
    "\\eqsim": "≂",
    "\\triangleq": "≜",
    "\\curlyeqprec": "⋞",
    "\\curlyeqsucc": "⋟",
    "\\gg": "≫",
    "\\gtreqless": "⋛",
    "\\ngeq": "≱",
    "\\geqq": "≧",
    "\\gtrless": "≷",
    "\\gneqq": "≩",
    "\\ngtr": "≯",
    "\\gnsim": "⋧",
    "\\gtrsim": "≳",
    "\\vartriangleright": "⊳",
    "\\trianglerighteq": "⊵",
    "\\ntrianglerighteq": "⋭",
    "\\ntriangleright": "⋫",
    "\\ggg": "⋙",
    "\\ll": "≪",
    "\\lesseqgtr": "⋚",
    "\\nleq": "≰",
    "\\leqq": "≦",
    "\\lessgtr": "≶",
    "\\lneqq": "≨",
    "\\nless": "≮",
    "\\lnsim": "⋦",
    "\\lesssim": "≲",
    "\\vartriangleleft": "⊲",
    "\\trianglelefteq": "⊴",
    "\\ntrianglelefteq": "⋬",
    "\\ntriangleleft": "⋪",
    "\\lll": "⋘",
    "\\approxeq": "≊",
    "\\prec": "≺",
    "\\precapprox": "⪷",
    "\\preceq": "⪯",
    "\\preccurlyeq": "⪯",
    "\\npreceq": "⋠",
    "\\precnapprox": "⪹",
    "\\nprec": "⊀",
    "\\precnsim": "⋨",
    "\\precsim": "≾",
    "\\succ": "≻",
    "\\succapprox": "⪸",
    "\\succeq": "⪰",
    "\\succcurlyeq": "⪰",
    "\\nsucceq": "⋡",
    "\\succnapprox": "⪺",
    "\\nsucc": "⊁",
    "\\succnsim": "⋩",
    "\\succsim": "≿",
    "\\equiv": "≡",
    "\\propto": "∝",
    "\\ni": "∋",
    "\\Subset": "⋐",
    "\\nsubseteq": "⊈",
    "\\sqsubseteq": "⊑",
    "\\subsetneq": "⊊",
    "\\supset": "⊃",
    "\\Supset": "⋑",
    "\\supseteq": "⊇",
    "\\nsupseteq": "⊉",
    "\\sqsupseteq": "⊒",
    "\\supsetneq": "⊋",
    "\\models": "⊧",
    "\\therefore": "∴",
    "\\because": "∵",
    "\\multimap": "⊸",
    "\\mid": "∣",
    "\\nmid": "∤",
    "\\parallel": "∥",
    "\\shortparallel": "∥",
    "\\nparallel": "∦",
    "\\perp": "⟂",
    "\\Join": "⨝",
    "\\vartriangle": "▵",
    "\\longmapsto": "⟼",
    "\\nRightarrow": "⇏",
    "\\hookrightarrow": "↪",
    "\\looparrowright": "↬",
    "\\nrightarrow": "↛",
    "\\rightsquigarrow": "⇝",
    "\\rightarrowtail": "↣",
    "\\Rrightarrow": "⇛",
    "\\twoheadrightarrow": "↠",
    "\\nLeftarrow": "⇍",
    "\\hookleftarrow": "↩",
    "\\looparrowleft": "↫",
    "\\nleftarrow": "↚",
    "\\leftarrowtail": "↢",
    "\\Lleftarrow": "⇚",
    "\\twoheadleftarrow": "↞",
    "\\uparrow": "↑",
    "\\Uparrow": "⇑",
    "\\downarrow": "↓",
    "\\Downarrow": "⇓",
    "\\nLeftrightarrow": "⇎",
    "\\nleftrightarrow": "↮",
    "\\leftrightsquigarrow": "↭",
    "\\updownarrow": "↕",
    "\\Updownarrow": "⇕",
    "\\nearrow": "↗",
    "\\searrow": "↘",
    "\\nwarrow": "↖",
    "\\swarrow": "↙",
    "\\circlearrowleft": "↺",
    "\\curvearrowleft": "↶",
    "\\circlearrowright": "↻",
    "\\curvearrowright": "↷",
    "\\rightrightarrows": "⇉",
    "\\leftleftarrows": "⇇",
    "\\upuparrows": "⇈",
    "\\downdownarrows": "⇊",
    "\\leftrightarrows": "⇆",
    "\\rightleftarrows": "⇄",
    "\\rightharpoonup": "⇀",
    "\\rightharpoondown": "⇁",
    "\\leftharpoonup": "↼",
    "\\leftharpoondown": "↽",
    "\\upharpoonleft": "↿",
    "\\upharpoonright": "↾",
    "\\downharpoonleft": "⇃",
    "\\downharpoonright": "⇂",
    "\\leftrightharpoons": "⇋",
    "\\rightleftharpoons": "⇌",
    "\\vdash": "⊢",
    "\\nvdash": "⊬",
    "\\vDash": "⊨",
    "\\nvDash": "⊭",
    "\\dashv": "⊣",
    "\\asymp": "≍",
    "\\circeq": "≗",
    "\\smallsmile": "⌣",
    "\\smile": "⌣",
    "\\doteq": "≐",
    "\\Vdash": "⊩",
    "\\Doteq": "≑",
    "\\Vvdash": "⊪",
    "\\gnapprox": "⪺",
    "\\ngeqslant": "≱",
    "\\@ngeqslant": "≱",
    "\\precneqq": "⪵",
    "\\gneq": "⪈",
    "\\backepsilon": "∍",
    "\\between": "≬",
    "\\blacktriangleleft": "◀",
    "\\blacktriangleright": "▶",
    "\\bowtie": "⋈",
    "\\Bumpeq": "≎",
    "\\bumpeq": "≏",
    "\\dashleftarrow": "⇠",
    "\\dashrightarrow": "⇢",
    "\\doteqdot": "≑",
    "\\eqcirc": "≖",
    "\\fallingdotseq": "≒",
    "\\frown": "⌢",
    "\\gggtr": "⋙",
    "\\imageof": "⊷",
    "\\leadsto": "⇝",
    "\\lessapprox": "⪅",
    "\\lesseqqgtr": "⪋",
    "\\llless": "⋘",
    "\\lnapprox": "⪉",
    "\\lneq": "⪇",
    "\\Lsh": "↰",
    "\\nVDash": "⊯",
    "\\nVdash": "⊮",
    "\\origof": "⊶",
    "\\owns": "∋",
    "\\pitchfork": "⋔",
    "\\restriction": "↾",
    "\\risingdotseq": "≓",
    "\\Rsh": "↱",
    "\\sqsubset": "⊏",
    "\\sqsupset": "⊐",
    "\\subseteqq": "⫅",
    "\\succneqq": "⪶",
    "\\supseteqq": "⫆",
    "\\supsetneqq": "⫌",
    "\\varpropto": "∝",
    "\\varsubsetneq": "⊊",
    "\\@varsubsetneq": "⊊",
    "\\varsubsetneqq": "⫋",
    "\\@varsubsetneqq": "⫋",
    "\\varsupsetneq": "⊋",
    "\\@varsupsetneq": "⊋",
    "\\varsupsetneqq": "⫌",
    "\\@varsupsetneqq": "⫌",
    "\\gtreqqless": "⪌",
    "\\thicksim": "~",
    "\\nleqslant": "≰",
    "\\@nleqslant": "≰",
    "\\nshortmid": "∤",
    "\\@nshortmid": "∤",
    "\\smallfrown": "⌢",
    "\\shortmid": "∣",
    "\\gtrapprox": "⪆",
    "\\thickapprox": "≈",
    "\\nshortparallel": "∦",
    "\\@nshortparallel": "∦",
    "\\not": "/",
}

export const binMapping = {
    "+": "+",
    "-": "−",
    "±": "±",
    "−": "−",
    "×": "×",
    "*": "*",
    "⊗": "⊗",
    "⊘": "⊘",
    "∘": "∘",
    "\\cdot": "·",
    "\\times": "×",
    "\\oplus": "⊕",
    "\\ominus": "⊖",
    "\\pm": "±",
    "\\mp": "∓",
    "\\div": "÷",
    "\\star": "⋆",
    "\\cap": "∩",
    "\\cup": "∪",
    "\\ast": "∗",
    "\\circledast": "⊛",
    "\\dagger": "†",
    "\\ddagger": "‡",
    "\\circleddash": "⊝",
    "\\odot": "⊙",
    "\\boxdot": "⊡",
    "\\dotplus": "∔",
    "\\boxplus": "⊞",
    "\\boxminus": "⊟",
    "\\otimes": "⊗",
    "\\divideontimes": "⋇",
    "\\leftthreetimes": "⋋",
    "\\rightthreetimes": "⋌",
    "\\ltimes": "⋉",
    "\\rtimes": "⋊",
    "\\boxtimes": "⊠",
    "\\gtrdot": "⋗",
    "\\lessdot": "⋖",
    "\\setminus": "∖",
    "\\And": "&",
    "\\bigcirc": "◯",
    "\\smallsetminus": "∖",
    "\\Cup": "⋓",
    "\\uplus": "⊎",
    "\\sqcup": "⊔",
    "\\Cap": "⋒",
    "\\sqcap": "⊓",
    "\\land": "∧",
    "\\wedge": "∧",
    "\\lor": "∨",
    "\\curlywedge": "⋏",
    "\\vee": "∨",
    "\\curlyvee": "⋎",
    "\\circ": "∘",
    "\\wr": "≀",
    "\\bullet": "•",
    "\\circledcirc": "⊚",
    "\\rhd": "△",
    "\\lhd": "◁",
    "\\bigtriangleup": "△",
    "\\bigtriangledown": "▽",
    "\\triangleright": "▹",
    "\\triangleleft": "◃",
    "\\diamond": "⋄",
    "\\amalg": "∐",
    "\\barwedge": "⊼",
    "\\centerdot": "⋅",
    "\\doublebarwedge": "⩞",
    "\\doublecap": "⋒",
    "\\doublecup": "⋓",
    "\\intercal": "⊺",
    "\\oslash": "⊘",
    "\\unlhd": "⊴",
    "\\unrhd": "⊵",
    "\\veebar": "⊻"
}

export const closeMapping = {
    ")": ")",
    "]": "]",
    "!": "!",
    "?": "?",
    "\\}": "}",
    "\\rvert": "|",
    "\\rVert": "‖",
    "\\rparen": ")",
    "\\rceil": "⌉",
    "\\rfloor": "⌋",
    "\\rbrack": "]",
    "\\rgroup": "⟯",
    "\\rangle": "⟩",
    "⟩": "⟩",
    "\\rbrace": "}",
    "\\lrcorner": "⌟",
    "\\@lrcorner": "⌟",
    "\\rmoustache": "⎱",
    "\\urcorner": "⌝",
    "\\@urcorner": "⌝",
}


export const openMapping = {
    "(": "(",
    "[": "[",
    "\\{": "{",
    "\\lvert": "|",
    "\\lVert": "‖",
    "\\lparen": "(",
    "\\lceil": "⌈",
    "\\lfloor": "⌊",
    "\\lbrack": "[",
    "\\lgroup": "⟮",
    "\\langle": "⟨",
    "⟨": "⟨",
    "\\lbrace": "{",
    "\\llcorner": "⌞",
    "\\@llcorner": "⌞",
    "\\lmoustache": "⎰",
    "\\ulcorner": "⌜",
    "\\@ulcorner": "⌜",
}

export const innerMapping = {
    "\\@cdots": "⋯",
    "\\ldots": "…",
    "\\ddots": "⋱",
    "\\mathellipsis": "…",
    "\\textellipsis": "…",
    "…": "…",
}

export const punctMapping = {
    ",": ",",
    ";": ";",
    "\\cdotp": "·",
    "\\ldotp": "."
}

export const atomMapping = {
    ...binMapping,
    ...closeMapping,
    ...openMapping,
    ...innerMapping,
    ...punctMapping,
    ...relMapping
}

export const lrMapping = {
    ...textordMapping,
    ...mathordMapping,
    ...atomMapping,
}

export const accentMapping = {
    "\\grave": "\u{0300}",
    "\\acute": "\u{0301}",
    "\\hat": "\u{0302}",
    "\\widehat": "\u{0302}",
    "\\^": "\u{0302}",
    "\\.": "\u{0307}",
    "\\\"": "\u{0308}",
    "\\tilde": "\u{0303}",
    "\\widetilde": "\u{0303}",
    "\\breve": "\u{0306}",
    "\\dot": "\u{0307}",
    "\\ddot": "\u{0308}",
    "\\dddot": "\u{20db}",
    "\\ddddot": "\u{20dc}",
    "\\H": "\u{030b}",
    "\\'": "´",
    "\\check": "\u{030c}",
    "\\widecheck": "\u{030c}",
    "\\u": "\u{0306}",
    "\\v": "\u{030c}",
    "\\r": "\u{030a}",
    "\\vec": "\u{20d7}",
    "\\overrightarrow": "\u{20d7}",
    "\\overleftarrow": "\u{20d6}",
    "\\mathring": "\u{030a}",
    "\\overleftrightarrow": "\u{20e1}",
    "\\overgroup": "\u{0311}",
    "\\overlinesegment": "\u{20e9}",
    "\\overleftharpoon": "\u{20d0}",
    "\\overrightharpoon": "\u{20d1}"
}

export const functionalAccentMappint = {
    "\\bar": "overline",
    "\\overline": "overline",
    "\\underline": "underline",
    "\\overbrace": "overbrace",
    "\\underbrace": "underbrace",
    "\\overbracket": "overbracket",
    "\\underbracket": "underbracket",
}

function textFunc(text) {
    return {
        func: "text",
        text: text
    }
}

function opTextFunc(text) {
    return {
        func: "op",
        text: {
            func: "text",
            text: text
        }
    }
}

export const opMapping = {
    "\\sin": opTextFunc("sin"),
    "\\cos": opTextFunc("cos"),
    "\\tan": opTextFunc("tan"),
    "\\cot": opTextFunc("cot"),
    "\\sec": opTextFunc("sec"),
    "\\csc": opTextFunc("csc"),
    "\\arcsin": opTextFunc("arcsin"),
    "\\arccos": opTextFunc("arccos"),
    "\\arctan": opTextFunc("arctan"),
    "\\sinh": opTextFunc("sinh"),
    "\\cosh": opTextFunc("cosh"),
    "\\tanh": opTextFunc("tanh"),
    "\\coth": opTextFunc("coth"),
    "\\ln": opTextFunc("ln"),
    "\\log": opTextFunc("log"),
    "\\lg": opTextFunc("lg"),
    "\\lim": opTextFunc("lim"),
    "\\limsup": opTextFunc("limsup"),
    "\\liminf": opTextFunc("liminf"),
    "\\hom": opTextFunc("hom"),
    "\\det": opTextFunc("det"),
    "\\exp": opTextFunc("exp"),
    "\\deg": opTextFunc("deg"),
    "\\gcd": opTextFunc("gcd"),
    "\\lcm": opTextFunc("lcm"),
    "\\dim": opTextFunc("dim"),
    "\\ker": opTextFunc("ker"),
    "\\arg": opTextFunc("arg"),
    "\\Pr": opTextFunc("Pr"),
    "\\max": opTextFunc("max"),
    "\\min": opTextFunc("min"),
    "\\argmax": opTextFunc("argmax"),
    "\\argmin": opTextFunc("argmin"),
    "\\sup": opTextFunc("sup"),
    "\\inf": opTextFunc("inf"),
    "\\th": opTextFunc("th"),
    "\\sum": textFunc("∑"),
    "\\prod": textFunc("∏"),
    "\\int": textFunc("∫"),
    "\\iint": textFunc("∬"),
    "\\iiint": textFunc("∭"),
    "\\oint": textFunc("∮"),
    "\\oiint": textFunc("∯"),
    "\\oiiint": textFunc("∰"),
    "\\bigsqcup": textFunc("⨆"),
    "\\bigvee": textFunc("⋁"),
    "\\bigwedge": textFunc("⋀"),
    "\\smallint": textFunc("∫"),
    "\\bigcup": textFunc("⋃"),
    "\\bigoplus": textFunc("⨁"),
    "\\bigotimes": textFunc("⨂"),
    "\\coprod": textFunc("∐"),
    "\\bigcap": textFunc("⋂"),
    "\\bigodot": textFunc("⨀"),
    "\\intop": textFunc("∫"),
    "\\biguplus": textFunc("⨄"),
}

export const xArrowMapping = {
    "\\xleftarrow": "⟵",
    "\\xrightarrow": "⟶",
    "\\xLeftarrow": "⟸",
    "\\xRightarrow": "⟹",
    "\\xleftrightarrow": "↔",
    "\\xLeftrightarrow": "⇔",
    "\\xhookleftarrow": "↩",
    "\\xhookrightarrow": "↪",
    "\\xtwoheadleftarrow": "↞",
    "\\xtwoheadrightarrow": "↠",
    "\\xleftharpoonup": "↼",
    "\\xrightharpoonup": "⇀",
    "\\xleftharpoondown": "↽",
    "\\xrightharpoondown": "⇁",
    "\\xleftrightharpoons": "⇋",
    "\\xrightleftharpoons": "⇌",
    "\\xtofrom": "⇄",
    "\\xmapsto": "↦",
    "\\xlongequal": "=",
}

export const negationMapping = {
    '\\in': '∉',
    '=': '≠',
    '\\equiv': '≢',
    '\\mid': '∤',
    '\\approx': '≉',
    '\\Rightarrow': '⇏',
    '\\Leftarrow': '⇍',
    '\\rightarrow': '↛',
    '\\leftarrow': '↚',
    '\\to': '↛',
    '\\leftrightarrow': '↮',
    '\\subset': '⊄',
    '\\subseteq': '⊈',
    '\\sqsubseteq': '⋢',
    '\\supset': '⊅',
    '\\vdash': '⊬',
    '\\parallel': '∦',
    '\\cong': "≇",
    "\\simeq": "≄",
    "\\leq": "≰",
    "\\prec": "⊀",
    "\\sim": "≁",
    "\\ni": "∌",
    "\\perp": "⟂",
    "\\gg": "≫",
    "\\ll": "≪",
    "\\propto": "∝",
};